services:
  bot_update_listener:
    build:
      context: docker/symfony
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME:-sunday-research-bot}.bot_update_listener"
    working_dir: "/app"
    depends_on:
      - redis
      - postgres
    volumes:
      - ".:/app"
    env_file: .env
    command: [ "/app/bin/console", "app:bot-update-listener" ]
    stop_signal: SIGQUIT # этот сигнал используется по умолчанию
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
          #pids: 1
        reservations:
          cpus: '0.50'
          memory: 128M
