include:
  - cli-commands.yaml

services:
  nginx:
    image: nginx:1.25.3-alpine3.18
    container_name: "${COMPOSE_PROJECT_NAME:-sunday-research-bot}.nginx"
    working_dir: "/app"
    volumes:
      - ".:/app"
      - "./docker/nginx/vhost:/etc/nginx/conf.d"
    ports:
      - "${SYMFONY_EXTERNAL_PORT:-8000}:80"
    healthcheck:
      test: [ "CMD-SHELL", "wget -O /dev/null http://127.0.0.1:80/health_nginx || exit 1" ]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 30s
  symfony:
    build:
      context: docker/symfony
      dockerfile: Dockerfile
    container_name: "${COMPOSE_PROJECT_NAME:-sunday-research-bot}.symfony"
    working_dir: "/app"
    depends_on:
      - nginx
      - redis
      - postgres
    volumes:
      - ".:/app"
    env_file: .env
    command: [ "/usr/local/sbin/php-fpm", "--nodaemonize" ]
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php-fpm > /dev/null" ]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 30s
  redis:
    image: redis:7.2.3-alpine3.19
    container_name: "${COMPOSE_PROJECT_NAME:-sunday-research-bot}.redis"
    volumes:
      - "./docker/redis/redis.conf:/etc/redis.conf"
    command: [ "redis-server", "/etc/redis.conf" ]
    ports:
      - "${REDIS_EXTERNAL_PORT:-6379}:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 30s
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: "${COMPOSE_PROJECT_NAME:-sunday-research-bot}.postgres"
    # set shared memory limit when using docker-compose
    shm_size: 256mb
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-sunday_research_bot}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB:-sunday_research_bot}"
      PGUSER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB:-sunday_research_bot}" ]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - "./docker/postgres/data:/var/lib/postgresql/data"
    ports:
      - "${POSTGRES_EXTERNAL_PORT:-5432}:5432"
